site_name: Material Design for MyNotes
site_description: 'A Material Design theme for MyNotes'
site_author: 'Anonymous'

# Repository
remote_branch: gh-pages
remote_name: origin
repo_name: 'Black-Gold/MyNotes'
repo_url: 'https://github.com/Black-Gold/MyNotes'

nav:
  - Home: 'index.md'
  - Vim: 'Vim.md' 
  - ProgramLanguages: 
    - 'BREs': 'BREs.md'
    - 'Shell': 'Shell.md'
    - 'Python3': 'Python3.md'
    - 'Lua': 'Lua.md'
    - 'Go': 'Go.md'
  - Linux&WinServer: 
    - 'Linux': 'Linux.md'
    - 'Iproute2&Net-tools': 'Utilities.md'
    - 'Iptables': 'Iptables.md'
    - 'Firewalld': 'Firewalld.md'
    - 'WindowsServer': 'Windows.md'
  - DevOps: 
    - 'Ansible': 'Ansible.md'
    - 'Apollo': 'Apollo.md'
  - WebServer: 
    - 'Nginx': 'Nginx.md'
    - 'Apache&PHP-FPM': 'Apache.md'
    - 'Tomcat': 'Tomcat.md'
    - 'WildFly': 'WildFly.md'
    - 'Caddy': 'Caddy.md'
  - OptimisingWebDelivery: 
    - 'Squid': 'Squid.md'
    - 'Varnish': 'Varnish.md'
    - 'Stunnel': 'Stunnel.md'
    - 'ApacheTrafficServer': 'TrafficServer.md'
  - CI&DC: 
    - 'Git&GitLab': 'Git.md'
    - 'Jenkins': 'Jenkins.md'
  - Database: 
    - 'MySQL': 'MySQL.md'
    - 'MariaDB': 'MariaDB.md'
    - 'Oracle': 'Oracle.md'
    - 'Redis': 'Redis.md'
    - 'Memcached': 'Memcached.md'
    - 'MongoDB': 'MongoDB.md'
    - 'PostgreSQL': 'PostgreSQL.md'
    - 'BigData': 'BigData.md'
  - LB&HA: 
    - 'LVS': 'LVS.md'
    - 'HAProxy': 'Haproxy.md'
    - 'Traefik': 'Traefik.md'
    - 'Envoy': 'Envoy.md'
  - MessageQueue: 
    - 'ActiveMQ': 'ActiveMQ.md'
    - 'TheNextGeneration_ActimveMQ': 'ActiveMQApollo.md'
    - 'Kafka': 'Kafka.md'
    - 'RabbitMQ': 'RabbitMQ.md'
  - ContainerEcosystem: 
    - 'Docker': 'Docker.md'
    - 'Kubernetes': 'Kubernetes.md'
    - 'OKD': 'OKD.md'
    - 'ContainerOS': 'Coreos.md'
  - Monitor: 
    - 'Zabbix': 'Zabbix.md'
    - 'ELKStack': 'Elk.md'
    - 'Prometheus': 'Prometheus.md'
    - 'Grafana': 'Grafana.md'
    - 'Nagios': 'Nagios.md'
    - 'OpenTSDB': 'OpenTSDB.md'
    - 'TICKStack': 'TICK.md'
    - 'SomelseMonitors': 'Monitors.md'
  - FileSystem: 
    - 'Ceph': 'Ceph.md'
    - 'GlusterFS': 'GlusterFS.md'
  - Network: 
    - 'Cisco': 'Cisco.md'
    - 'Huawei&H3C': 'HW3C.md'
  - CrossGFW: 
    - 'VPN': 'VPN.md'
  - Security: 
    - 'Snort': 'Snort.md'
  - TreasureTheLeisure:
    - 'GoogleTricks': 'GoogleTricks.md'
    - 'Voip': 'Voip.md'
    - 'Raspberrypi': 'Raspberrypi.md'

theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'green'
    accent: 'light green'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: 'images/favicon.ico'

extra:
  search:
    language:'zh,en,de,ru,jp'
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/Black-Gold'
    - type: 'instagram'
      link: 'https://www.instagram.com/black0gold/'

google_analytics: 
  - 'UA-131093963-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

#extra_css:
#  - 'stylesheets/extra.css'

#extra_javascript:
#  - 'javascripts/extra.js'