site_name: Material Design for MyNotes
site_description: 'A Material Design theme for MyNotes'
site_author: 'Anonymous'

# Repository
remote_branch: gh-pages
remote_name: origin
repo_name: 'Black-Gold/MyNotes'
repo_url: 'https://github.com/Black-Gold/MyNotes'

nav:
  - Home: 'index.md'
  - Version Control: 
    - 'Git': 'Git.md'
  - Vim: 'Vim.md'
  - Shell: 
    - 'BREs': 'BREs.md'
    - 'ShellNotes': 'ShellNotes.md'
  - Python3: 'python3.md'
  - AboutLinux: 
    - 'AboutLinux': 'AboutLinux.md'
    - 'Debian': 'Debian.md'
    - 'Iproute': 'iproute.md'
  - HTTP Server: 
    - 'Nginx': 'Nginx.md'
    - 'Apache': 'Apache.md'
  - 'ActiveMQ': 'ActiveMQ.md'
  - HAProxy&Cache: 
    - 'HAProxy': 'Haproxy.md'
  - Ansible: 'ansible.md'
  - CI&DC: 
    - 'Jenkins': 'Jenkins.md'
  - FileSystem: 
    - 'Ceph': 'Ceph.md'
    - 'Vsftp': 'Vsftp.md'
  - Container: 
    - 'Docker': 'docker.md'
    - 'Kubernetes': 'Kubernetes.md'
    - 'Paas': 'OKD.md'
    - 'Container OS': 'Croreos.md'
  - Tomcat: 'Tomcat.md'
  - Data: 
    - 'MySQL': 'MySQL.md'
    - 'Oracle': 'Oracle.md'
    - 'Redis': 'redis.md'
    - 'Memcached': 'memcached.md'
  - Monitor: 
    - 'Zabbix': 'Zabbix.md'
    - 'Nagios': 'Nagios.md'
    - 'Nagios': 'Nagios.md'
    - 'Prometheus': 'Prometheus.md'
    - 'Grafana': 'Grafana.md'
    - 'SomelseMonitors': 'Monitors.md'
  - CrossGFW: 
    - 'VPN': 'VPN.md'
    - 'Shadowsocks': 'shadowsocks.md'
  - Others:
    - DNS: 'DNS.md'
    - Mail: 'Mail.md'
    - Samba: 'Samba.md'
    - AD&FileSystem: 'AD&FileSystem.md'
    - PHP: 'PHP.md'
    - Raspberrypi: 'Raspberrypi.md'
    - GoogleTricks: 'GoogleTricks.md'
    - freeswitch: 'freeswitch.md'
    - Sipcode: 'sipcode.md'
  - LinuxCommandAll: 
    - 'ab': 'ab.md'

theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'green'
    accent: 'light green'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: 'images/favicon.ico'

extra:
  search:
    language:'zh,en,de,ru,jp'
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/Black-Gold'
    - type: 'Instagram'
      link: 'https://www.instagram.com/black0gold/'

google_analytics: ['UA-131093963-1', '19950128.com']

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

#extra_css:
#  - 'stylesheets/extra.css'

#extra_javascript:
#  - 'javascripts/extra.js'