site_name: Material Design for MyNotes
site_description: 'A Material Design theme for MyNotes'
site_author: 'Anonymous'

# Repository
remote_branch: gh-pages
remote_name: origin
repo_name: 'Black-Gold/MyNotes'
repo_url: 'https://github.com/Black-Gold/MyNotes'

nav:
  - Home: 'index.md'
  - Vim: 'Vim.md'
  - VersionControl: 
    - 'Git': 'Git.md'
  - ProgramLanguages: 
    - 'BREs': 'BREs.md'
    - 'Shell': 'Shell.md'
    - 'Python3': 'Python3.md'
    - 'Lua': 'Lua.md'
    - 'Go': 'Go.md'
  - AboutLinux: 
    - 'Linux': 'Linux.md'
    - 'Debian': 'Debian.md'
    - 'Iproute': 'Iproute.md'
    - 'Firewalld': 'Firewalld.md'
  - WebServer: 
    - 'Nginx': 'Nginx.md'
    - 'Apache': 'Apache.md'
    - 'Tomcat': 'Tomcat.md'
    - 'WildFly': 'WildFly.md'
    - 'Caddy': 'Caddy.md'
  - CI&DC: 
    - 'Jenkins': 'Jenkins.md'
  - Monitor: 
    - 'Zabbix': 'Zabbix.md'
    - 'Prometheus': 'Prometheus.md'
    - 'Grafana': 'Grafana.md'
    - 'Nagios': 'Nagios.md'
    - 'TICKStack': 'TICK.md'
    - 'OpenTSDB': 'OpenTSDB.md'
    - 'SomelseMonitors': 'Monitors.md'
  - ConfigManagement: 
    - 'Apollo': 'Apollo.md'
  - OptimisingWebDelivery: 
    - 'Squid': 'Squid.md'
    - 'Varnish': 'Varnish.md'
    - 'Stunnel': 'Stunnel.md'
    - 'ApacheTrafficServer': 'TrafficServer.md'
    - 'Memcached': 'Memcached.md'
  - LB&HA: 
    - 'LVS': 'LVS.md'
    - 'Keepalived': 'Keepalived.md'
    - 'HAProxy': 'Haproxy.md'
    - 'Traefik': 'Traefik.md'
    - 'Envoy': 'Envoy.md'
  - ContainerEcosystem: 
    - 'Docker': 'Docker.md'
    - 'Kubernetes': 'Kubernetes.md'
    - 'Paas': 'OKD.md'
    - 'ContainerOS': 'Croreos.md'
  - Database: 
    - 'MySQL': 'MySQL.md'
    - 'MariaDB': 'MariaDB.md'
    - 'Oracle': 'Oracle.md'
    - 'Redis': 'Redis.md'
    - 'Cassandra': 'Cassandra.md'
    - 'MongoDB': 'MongoDB.md'
    - 'PostgreSQL': 'PostgreSQL.md'
  - OpsTools: 
    - 'Ansible(ITAutomationTool)': 'Ansible.md'
    - 'ELKStack': 'Elk.md'
  - MessageQueue: 
    - 'ActiveMQ': 'ActiveMQ.md'
    - 'ActiveMQ Apollo': 'ActiveMQApollo.md'
    - 'RabbitMQ': 'RabbitMQ.md'
    - 'Kafka': 'Kafka.md'
  - FileSystem: 
    - 'Ceph': 'Ceph.md'
    - 'Vsftp': 'Vsftp.md'
  - Security: 
    - 'Snort': 'Snort.md'
  - Network: 
    - 'DNS': 'DNS.md'
    - 'Cisco': 'Cisco.md'
    - 'Huawei': 'Huawei.md'
  - CrossGFW: 
    - 'VPN': 'VPN.md'
    - 'Shadowsocks': 'Shadowsocks.md'
  - TreasureTheLeisure:
    - 'Mail': 'Mail.md'
    - 'Samba': 'Samba.md'
    - 'Windows': 'Windows.md'
    - 'Raspberrypi': 'Raspberrypi.md'
    - 'GoogleTricks': 'GoogleTricks.md'
    - 'Freeswitch': 'Freeswitch.md'
    - 'Asterisk': 'Asterisk.md'
    - 'Sipcode': 'Sipcode.md'
    - 'PHP': 'PHP.md'

theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'green'
    accent: 'light green'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: 'images/favicon.ico'

extra:
  search:
    language:'zh,en,de,ru,jp'
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/Black-Gold'
    - type: 'instagram'
      link: 'https://www.instagram.com/black0gold/'

google_analytics: 
  - 'UA-131093963-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

#extra_css:
#  - 'stylesheets/extra.css'

#extra_javascript:
#  - 'javascripts/extra.js'